apiVersion: v1
kind: ConfigMap
metadata:
  name: facebook-configmap
data:
  config.php: |
        <?php
        $db_host = "mysql";
        $db_user = "mysql";
        $db_pass = "password";
        $db_name = "db_sosmed";
        try {
        //create PDO connection
        $db = new PDO("mysql:host=$db_host;dbname=$db_name", $db_user, $db_pass);
        } catch(PDOException $e) {
        //show error
        die("Terjadi masalah: " . $e->getMessage());
        }
